package repository.exceptions;

public class ObjectAlreadyContained extends Exception{
    public ObjectAlreadyContained() {
        super("Object already contained!");
    }
}
